version: "3.9"
services:
  webserve:
    build: ./requirements/nginx
    ports: "443:443"
    env_file: .env
  app:
    build: ./requirements/wordpress
  db:
    build: ./requirements/mariadb
volumes:
networks:

