version: "3.3"
services: 
  nginx:
    build: ./requirements/nginx
    container_name: local_nginx
    image: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - net
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    expose:
      - "3306"

networks:
  net:
