version: "3"

services:
  webserve:
    container_name: nginx
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    networks:
      - wordpress
    ports:
      - "443:443" 
    volumes:
      - wp-volume:/var/www
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    volumes:
     - wp-volume:/var/www
    networks:
      - wordpress
    env_file: ./.env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - wordpress
    env_file: ./.env
    restart: always

  ftp:
    container_name: ftp
    build:
      context: .
      dockerfile: ./requirements/bonus/ftp/Dockerfile
    volumes:
      - wp-volume:/home/kamal/ftp/files
    networks:
      - wordpress
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    env_file: ./.env
    depends_on:
      - wordpress
    restart: always
  
  redis:
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - wordpress
    restart: always

  adminer:
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
     - wordpress
    restart: always

  webstatic:
    container_name: static_website
    build:
      context: .
      dockerfile: requirements/bonus/website_static/Dockerfile
    ports:
      - "80:80"
    restart: always

  portainer:
    container_name: portainer
    build:
      context: .
      dockerfile: requirements/bonus/portainer/Dockerfile
    ports:
      - "9000:9000"
    restart: always

volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wp
      o: bind
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind

networks:
  wordpress:
    driver: bridge
